In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [5]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [6]:
df.drop(['deck', 'embark_town','alive', 'class', 'who','adult_male'],axis=1,inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [8]:
df['age'].fillna(df['age'].mean(),inplace=True)

In [9]:
df.dropna(subset=['embarked'],inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['sex']=le.fit_transform(df['sex'])
df['embarked']=le.fit_transform(df['embarked'])
df=df.astype({'alone':'int'})

In [12]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2      0
1         1       1    0  38.0      1      0  71.2833         0      0
2         1       3    0  26.0      0      0   7.9250         2      1
3         1       1    0  35.0      1      0  53.1000         2      0
4         0       3    1  35.0      0      0   8.0500         2      1

In [13]:
X=df.drop('survived',axis=1)
y=df['survived']

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
lr=LogisticRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
confusion_matrix(y_test,y_pred)

array([[90, 19],
       [16, 53]])

In [16]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178

In [17]:
# naive bayes without scaler
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_train,y_train)
y_predn=nb.predict(X_test)
confusion_matrix(y_test,y_predn)

array([[84, 25],
       [15, 54]])

In [18]:
print(classification_report(y_test,y_predn))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178

In [19]:
Xk = df.drop('survived', axis=1)
yk = df['survived']

In [20]:
# StandardScaler
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_k=sc.fit_transform(Xk)
X_k=pd.DataFrame(X_k,columns=Xk.columns)

In [21]:
from sklearn.model_selection import train_test_split
X_traink,X_testk,y_traink,y_testk=train_test_split(X_k,yk,test_size=0.2,random_state=42)

In [22]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_traink,y_traink)
y_predk=knn.predict(X_testk)
print(classification_report(y_testk,y_predk))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178

In [23]:
confusion_matrix(y_testk,y_predk)

array([[90, 19],
       [16, 53]])

In [24]:
# naive bayes using scaler
nb.fit(X_traink,y_traink)
y_prednk=nb.predict(X_testk)
print(classification_report(y_testk,y_prednk))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178

In [25]:
# decision tree classifier
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=42)
dt.fit(X_traink,y_traink)
y_predt=dt.predict(X_testk)
print(classification_report(y_testk,y_predt))

              precision    recall  f1-score   support

           0       0.83      0.73      0.78       109
           1       0.65      0.77      0.70        69

    accuracy                           0.75       178
   macro avg       0.74      0.75      0.74       178
weighted avg       0.76      0.75      0.75       178

In [26]:
# SVM
from sklearn.svm import SVC
svm=SVC(kernel='rbf')
svm.fit(X_traink,y_traink)
y_predsv=svm.predict(X_testk)
print(classification_report(y_testk,y_predsv))

              precision    recall  f1-score   support

           0       0.86      0.83      0.85       109
           1       0.75      0.78      0.77        69

    accuracy                           0.81       178
   macro avg       0.80      0.81      0.81       178
weighted avg       0.82      0.81      0.82       178

In [27]:
# cross validation
df

     survived  pclass  sex        age  sibsp  parch     fare  embarked  alone
0           0       3    1  22.000000      1      0   7.2500         2      0
1           1       1    0  38.000000      1      0  71.2833         0      0
2           1       3    0  26.000000      0      0   7.9250         2      1
3           1       1    0  35.000000      1      0  53.1000         2      0
4           0       3    1  35.000000      0      0   8.0500         2      1
..        ...     ...  ...        ...    ...    ...      ...       ...    ...
886         0       2    1  27.000000      0      0  13.0000         2      1
887         1       1    0  19.000000      0      0  30.0000         2      1
888         0       3    0  29.699118      1      2  23.4500         2      0
889         1       1    1  26.000000      0      0  30.0000         0      1
890         0       3    1  32.000000      0      0   7.7500         1      1

[889 rows x 9 columns]

In [28]:
X=df.drop('survived',axis=1)
y=df['survived']

In [29]:
from sklearn.model_selection import cross_val_score

In [30]:
# StandardScaler
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_s=sc.fit_transform(X)
X_s=pd.DataFrame(X_s,columns=X.columns)

In [32]:
scores=cross_val_score(svm,X_s,y,cv=5,scoring='accuracy')

In [34]:
scores.mean()

np.float64(0.8279375357074844)