In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X=df.drop('species',axis=1)
y=df['species']

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
model_k=KNeighborsClassifier(n_neighbors=7)
model_k.fit(X_train,y_train)
y_pred=model_k.predict(X_test)

In [18]:
model_k.score(X_test,y_test)

0.9666666666666667

In [19]:
from sklearn.svm import SVC
model_s=SVC(C=30,kernel='rbf',gamma='auto')
model_s.fit(X_train,y_train)
model_s.score(X_test,y_test)

1.0

In [22]:
# grid search cv
from sklearn.model_selection import GridSearchCV
model=SVC()

In [23]:
classifier=GridSearchCV(model,param_grid={'C':[1,10,20,30],'kernel':['rbf','linear'],'gamma':['auto','scale']},cv=5,return_train_score=False)

In [24]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20, 30], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear']})

In [26]:
result=pd.DataFrame(classifier.cv_results_)

In [29]:
result[['param_C','param_kernel','mean_test_score']]

    param_C param_kernel  mean_test_score
0         1          rbf         0.980000
1         1       linear         0.980000
2         1          rbf         0.966667
3         1       linear         0.980000
4        10          rbf         0.980000
5        10       linear         0.973333
6        10          rbf         0.980000
7        10       linear         0.973333
8        20          rbf         0.966667
9        20       linear         0.966667
10       20          rbf         0.980000
11       20       linear         0.966667
12       30          rbf         0.960000
13       30       linear         0.960000
14       30          rbf         0.973333
15       30       linear         0.960000

In [38]:
# RandomizedSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [34]:
classifier_r=RandomizedSearchCV(model,param_distributions={'C':[1,10,20,30],'kernel':['rbf','linear'],'gamma':['auto','scale']},n_iter=8,cv=5,return_train_score=False)

In [35]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=8,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'gamma': ['auto', 'scale'],
                                        'kernel': ['rbf', 'linear']})

In [36]:
result_r=pd.DataFrame(classifier_r.cv_results_)

In [37]:
result_r[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       20          rbf         0.966667
1       20       linear         0.966667
2       10          rbf         0.980000
3       10       linear         0.973333
4       30       linear         0.960000
5       20       linear         0.966667
6        1       linear         0.980000
7        1          rbf         0.966667